In [1]:
TE = joinpath(tempdir(), "OnePiece.test")

mkpath(TE)

"/var/folders/mg/30npdf0s1z36txb2qvgylrzh0000gn/T/OnePiece.test"

In [2]:
#using Revise
using BenchmarkTools

using OnePiece

## compare_with_target

In [3]:
n_ro = 5

n_co = 4

n_ze = convert(Int64, n_co / 2)

n_on = n_co - n_ze

2

In [4]:
bi_ = convert(BitVector, [zeros(n_ze); ones(n_on)])

4-element BitVector:
 0
 0
 1
 1

In [5]:
ve = [10^(id - 1) for id in 1:n_co]

4-element Vector{Int64}:
    1
   10
  100
 1000

In [6]:
ma = convert(Matrix, reshape(1:(n_ro * n_co), (n_ro, n_co)))

5×4 Matrix{Int64}:
 1   6  11  16
 2   7  12  17
 3   8  13  18
 4   9  14  19
 5  10  15  20

In [7]:
OnePiece.feature_by_sample.compare_with_target(bi_, ma, "signal_to_noise_ratio")

5-element Vector{Float64}:
 -1.923076923076923
 -1.8518518518518516
 -1.7857142857142858
 -1.7241379310344827
 -1.6666666666666667